name: s3-deploy

on:
  push:
    branch:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout source code
        run: actions/checkout@main

      - name: Install Dependencies # 의존 파일 설치
        run: npm install

      - name: Build # React Build
        run: npm run build

      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            dist s3://react-webpack-jun
